name: Pipeline
on: push
jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest

    steps:
      - name: print hello GitHub Actions
        run: echo "hello GitHub Actions"
      - name: checkout the project
        uses: actions/checkout@v2
        







