name: Pipeline
on: push
jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest

    steps:
      - name: print hello GitHub Actions
        run: echo "hello GitHub Actions"
      - name: checkout the project
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: build app
        run: npm run build
      - name: test app
        run: npm run test







